/*
	Name: 160th SOR USMC Mod
	Author: Buck & (Scooby - Initial Framework)
	Date: 16/07/16
	Description: cfgPatches.hpp
*/

class CfgPatches
{
	class SOR_Marines_Loadouts
	{
		units[] =
		{
			//Woodland Marpat//
			"SOR_ZeusCommand_M",
			"SOR_Actual_M",
			"SOR_Commander_M",
			"SOR_MechCommand_M",
			"SOR_AirCommand_M",
			"SOR_RTO_M",
			"SOR_TeamLeader_M",
			"SOR_Medic_M",
			"SOR_SPAR16S_M",
			"SOR_M240_M",
			"SOR_Grenadier_M",
			"SOR_Rifleman_M",
			"SOR_Rifleman_ammo_M",
			"SOR_RiflemanAT_M",
			"SOR_HeliPilot_M",
			"SOR_HeliCrew_M",
			"SOR_JetPilot_M",
			"SOR_MEVPilot_M",
			"SOR_ParaJumper_M",
			"SOR_ReconLeader_M",
			"SOR_ReconJTAC_M",
			"SOR_ReconRifleman_M",
			"SOR_Marksman_M",
			"SOR_ReconLeaderScuba_M",
			"SOR_ReconJTACScuba_M",
			"SOR_ReconRiflemanScuba_M",
			"SOR_MarksmanScuba_M",
			"SOR_Spotter_M",
			"SOR_Sniper_M",
			"SOR_MechCrew_M",
			"SOR_MechOperator_M",
			"SOR_MechCrewCommander_M",
			"SOR_MechDriver_M",
			"SOR_HMGActual_M",
			"SOR_HMGGunner_M",
			"SOR_HMGCarrier_M",
			"SOR_HMGRFL_M",
			"SOR_MORActual_M",
			"SOR_MORGunner_M",
			"SOR_MORCarrier_M",
			"SOR_MORRFL_M",
			"SOR_TL_Engineer_M",
			"SOR_Engineer_M",

			//Desert Marpat//
            "SOR_ZeusCommand_D_M",
			"SOR_Actual_D_M",
			"SOR_Commander_D_M",
			"SOR_MechCommand_D_M",
			"SOR_AirCommand_D_M",
			"SOR_RTO_D_M",
			"SOR_TeamLeader_D_M",
			"SOR_Medic_D_M",
			"SOR_SPAR16S_D_M",
			"SOR_M240_D_M",
			"SOR_Grenadier_D_M",
			"SOR_Rifleman_D_M",
			"SOR_Rifleman_ammo_D_M",
			"SOR_RiflemanAT_D_M",
			"SOR_HeliPilot_D_M",
			"SOR_HeliCrew_D_M",
			"SOR_JetPilot_D_M",
			"SOR_MEVPilot_D_M",
			"SOR_ParaJumper_D_M",
			"SOR_ReconLeader_D_M",
			"SOR_ReconJTAC_D_M",
			"SOR_ReconRifleman_D_M",
			"SOR_Marksman_D_M",
			"SOR_ReconLeaderScuba_D_M",
			"SOR_ReconJTACScuba_D_M",
			"SOR_ReconRiflemanScuba_D_M",
			"SOR_MarksmanScuba_D_M",
			"SOR_Spotter_D_M",
			"SOR_Sniper_D_M",
			"SOR_MechCrew_D_M",
			"SOR_MechOperator_D_M",
			"SOR_MechCrewCommander_D_M",
			"SOR_MechDriver_D_M",
			"SOR_HMGActual_D_M",
			"SOR_HMGGunner_D_M",
			"SOR_HMGCarrier_D_M",
			"SOR_HMGRFL_D_M",
			"SOR_MORActual_D_M",
			"SOR_MORGunner_D_M",
			"SOR_MORCarrier_D_M",
			"SOR_MORRFL_D_M",
			"SOR_TL_Engineer_D_M",
			"SOR_Engineer_D_M",

			//Land Vehicles//
			"SOR_USMC_rhsusf_m1a1hc_wd",
			"SOR_USMC_rhsusf_m1a1fep_od",
			"SOR_USMC_rhsusf_m1a1fep_d",
			"SOR_USMC_B_T_LSV_01_armed_F",
			"SOR_USMC_B_T_LSV_01_unarmed_F",
			"SOR_USMC_B_T_LSV_01_armed_desert_F",
			"SOR_USMC_B_T_LSV_01_unarmed_desert_F",
			"SOR_USMC_B_CTRG_LSV_01_light_F",
			"SOR_USMC_B_Quadbike_01_F",
			"SOR_USMC_B_Quadbike_01_F_inf",
			"SOR_USMC_B_APC_Wheeled_01_cannon_F",
			"SOR_USMC_B_APC_Wheeled_01_cannon_F_W",
			"SOR_USMC_I_APC_Wheeled_03_cannon_F",
			"SOR_USMC_B_MRAP_01_hmg_F",
			"SOR_USMC_B_MRAP_01_gmg_F",
			"SOR_USMC_B_MRAP_01__F",
			"SOR_USMC_B_MRAP_01_Engineer_F",
			"SOR_USMC_B_MRAP_01_hmg_F_W",
			"SOR_USMC_B_MRAP_01_gmg_F_W",
			"SOR_USMC_B_MRAP_01_F_W",
			"SOR_USMC_B_MRAP_01_Engineer_F_W",
			"SOR_USMC_I_MRAP_03_hmg_F",
			"SOR_USMC_I_MRAP_03_gmg_F",
			"SOR_USMC_I_MRAP_03_F",
			"SOR_USMC_I_MRAP_03_F_Engineer_F",
			"SOR_USMC_rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd",
			"SOR_USMC_rhsusf_M978A4_BKIT_usarmy_wd",
			"SOR_USMC_rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd",
			"SOR_USMC_rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d",
			"SOR_USMC_rhsusf_M978A4_BKIT_usarmy_d",
			"SOR_USMC_rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d",
			"SOR_USMC_B_MBT_01_arty_F",
			"SOR_USMC_B_MBT_01_mlrs_F",
			"SOR_USMC_B_APC_Tracked_01_AA_F",
			"SOR_USMC_B_APC_Tracked_01_CRV_F",

			//Water Vehicles//
			"SOR_USMC_B_Boat_Armed_01_minigun_F",
			"SOR_USMC_I_C_Boat_Transport_02_F",
			"SOR_USMC_rhsusf_mkvsoc",
			"SOR_USMC_C_Scooter_Transport_01_F",
			"SOR_USMC_V_B_Boat_Transport_01_F",
			"SOR_USMC_B_Boat_Transport_01_F",
			"SOR_USMC_B_SDV_01_F",

            //Air Vehicles//
			"SOR_USMC_RHS_UH1Y_d",
			"SOR_USMC_RHS_UH1Y_FFAR_d",
			"SOR_USMC_RHS_UH1Y_d_GS",
			"SOR_USMC_RHS_UH1Y_UNARMED_d_MEV",
			"SOR_USMC_rhsusf_CH53E_USMC_D",
			"SOR_USMC_RHS_AH1Z",
			"SOR_USMC_RHS_AH1Z_GS",
			"SOR_USMC_RHS_AH1Z_CS",
			"SOR_USMC_B_T_VTOL_01_armed_F",
			"SOR_USMC_B_T_VTOL_01_infantry_F",
			"SOR_USMC_B_T_VTOL_01_vehicle_F",
			"SOR_USMC_B_T_UAV_03_F",
			"SOR_USMC_B_UAV_02_F",
			"SOR_USMC_B_UAV_02_CAS_F",
			"SOR_USMC_B_UAV_01_F",
			"SOR_USMC_B_UGV_01_F",
			"SOR_USMC_B_UGV_01_rcws_F",
			"SOR_USMC_rhsusf_f22",
			"SOR_USMC_RHS_A10",
			"SOR_USMC_RHS_A10_AT",
			"SOR_USMC_RHS_C130J",

            //Boxes and Crates//
			"SOR_USMC_Ammo_box",
			"SOR_USMC_Weapons_box",
			"SOR_USMC_Equipment_box",
			"SOR_USMC_Explosives_box",
			"SOR_USMC_Explosives_Mines_box",
			"SOR_USMC_Grenades_box",
			"SOR_USMC_Launchers_basic_box",
			"SOR_USMC_Launchers_adv_box",
			"SOR_USMC_Launchers_adv_ammo_box",
			"SOR_USMC_Viper_ammo",
			"SOR_USMC_Viper_accessories",
			"SOR_USMC_General_accessories",
			"SOR_USMC_PJ_Uniforms_box",
			"SOR_USMC_PJ_Medical_box",
			"SOR_USMC_Parachute_box",
			"SOR_USMC_Ammo_crate",
			"SOR_USMC_Ammo_med_crate",
			"SOR_USMC_M2_crate",
			"SOR_USMC_Mortar_crate",
			"SOR_USMC_Heavy_weapons_crate",
			"SOR_USMC_Veh_Ammo_MRAP_crate",
			"SOR_USMC_Veh_Ammo_IFVAPC_crate",
			"SOR_USMC_Veh_Ammo_ARTYAA_crate",
			"SOR_USMC_Construction_crate"
		};
		weapons[] =
		{
			//Designated Marksmen Rifles//
			"160_rhs_weap_m14ebrri_leupold",

            //Assault Rifle//
			"160_rhs_weap_mk18_grip_bk_acog",
			"160_rhs_weap_mk18_m320_acog",
			"160_rhs_weap_mk18_grip_KAC_wd_acog",
			"160_rhs_weap_mk18_grip_KAC_d_acog",
            "160_rhs_weap_m4a1_blockII_grip_KAC_eotech",
            "160_rhs_weap_mk18_eotech",
            "160_rhs_weap_m4_pmag_eotech",
            "160_rhs_weap_mk18_cco",

            //Squad Automatic Weapon//
            "160_rhs_weap_m27iar_grip_eotech",
            "160_rhs_weap_m249_pip_S_para_eotech",

            //Light Machine Gun//
			"160_rhs_weap_m240G_specter",

			//Sub Machine Guns//
			"160_rhsusf_weap_MP7A1_base_f_eotech",

			//Sniper Rifles//
			"160_rhs_weap_M107_w_premier",
			"160_rhs_weap_m24sws_blk_premier",

			//Pistols//
			"160_hgun_P07_F_viper"
		};
	};
};
